services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: bundle exec foreman start -f Procfile.dev
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379/0
  db:
    image: postgres:17.4-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image:  redis:6.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  redis_data:
