default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: technical_exercise_development

test:
  <<: *default
  database: technical_exercise_test
